### ISSUE TITLE
ADMIN: Epostlistan listar alla mailadresser med ett ”, ” mellan från alla kunder som vill ha ett nyhetsbrev

### ISSUE THREAD

**Issue by ThommyDude** [ThommyDude/updated-e-shop#14]

**Comment by ThommyDude** [comment]
Vad är den här bra för?
Jag visar i kundlista vem som har sagt ja eller nej till att få nyhetsbrevet. Så blir inte den här lite onödigt?

❓

**Comment by kemikal** [comment]
För att en ”admin” enkelt skall kunna importera epostadresserna till en maillista i något externt program. Info uppdelat med en ”, ” brukar kallas för ett csv format som enkelt går att importera in i tex mailchimp.

**Comment by ThommyDude** [comment]
👌
