### ISSUE TITLE
Klickar vi på en produkt ska vi komma till en produktsida med mer info.

### ISSUE THREAD

**Issue by ThommyDude** [ThommyDude/updated-e-shop#6]

**Comment by ThommyDude** [comment]
Man behöver klicka på en _show more_ men man kommer till en mer info sida.

Där emot så visar den inte riktig nån ny information, eftersom det inte **_FINNS_** nån mer information.
Behöver detta fixas?

❓

**Comment by kemikal** [comment]
Nej du kan köra ”placeholders” eller på annat sätt visa att detta är en sida med plats för mer info. Kan vara samma för alla produktsidor (förutom själva produkten då). Tex hör kanske man vill visa en större bild, mer information osv!

**Comment by ThommyDude** [comment]
👌
